// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foqhocltsinjrazasqez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvcWhvY2x0c2luanJhemFzcWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzEwODUsImV4cCI6MjA2NzQwNzA4NX0.WbXVRdCUI4izUGBEi2N8useqZW_Uj0ygsPAIjTVtvkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});